### ISSUE TITLE
registrySubsetRules not working

### ISSUE THREAD

**Issue by Akryum** [algolia/npm-search#235] opened 2018-07-04 22:17 UTC
It seems that the [framework-specific rules](https://github.com/algolia/npm-search/blob/master/src/formatPkg.js#L207) are no longer working:

[Babel Repl](https://screenshots.firefox.com/DMStzwhRJR0Dp3xz/babeljs.io)

[Vue CLI UI](https://screenshots.firefox.com/KrmLSp4iwUxa3Stx/localhost)

**Comment by Haroenv** [comment] 2018-07-05 07:08
Oh no, that’s definitely wrong

**Comment by Haroenv** [comment] 2018-07-05 07:20
I temporarily fixed it by setting the settings again, but seems like after bootstrap no settings are set. I suspect #233 has the same cause, so I'll close this one.

It might have something to do with how settings are set in the index, but not really sure for now.

Duplicate of #233

**Closed by Haroenv** 2018-07-05 07:20 UTC
